#ifndef _APP_DATA_CENTER_H
#define _APP_DATA_CENTER_H

#define LED_CTRL_THREAD_STACK 1024
#define LED_CTRL_THREAD_PRIORITY 3
#define LED_CTRL_THREAD_TICK 20

#define MQTT_SERVICE_THREAD_STACK 1024
#define MQTT_SERVICE_THREAD_PRIORITY 3
#define MQTT_SERVICE_THREAD_TICK 20

#define LLCC68_SERVICE_THREAD_STACK 1024                            
#define LLCC68_SERVICE_THREAD_PRIORITY 3
#define  LLCC68_SERVICE_THREAD_TICK 20 

#endif